name: Latest books
on:
  schedule:
    # Run it every hour once
    - cron: "0 0/12 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update the Readme file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: zwacky/goodreads-profile-workflow@v1
        name: Update books currently reading
        with:
          # Replace this with your goodreads user id (go to "My Books" on goodreads to see it in the URL)
          goodreads_user_id: "53478182"
          shelf: "currently-reading"
          max_books_count: "5"
      - uses: zwacky/goodreads-profile-workflow@v1
        name: Update books already read
        with:
          # Replace this with your goodreads user id (go to "My Books" on goodreads to see it in the URL)
          goodreads_user_id: "53478182"
          shelf: "read"
          max_books_count: "3"
          comment_tag_name: "GOODREADS-LIST-PAST"
